-- Shared database schema for the album app.
-- Tables are in Spanish to match the app, and `user` is avoided because it is reserved in SQL dialects.

drop table if exists public.paises cascade;

create table if not exists public.usuarios (
  id bigint generated by default as identity primary key,
  name text not null,
  login_name text not null,
  login_password text not null,
  lamina_path text not null default '',
  created_at timestamptz not null default now()
);

create extension if not exists pgcrypto;
create extension if not exists unaccent;

create or replace function public.strip_diacritics(
  p_text text
)
returns text
language sql
immutable
set search_path = public
as $$
  select unaccent(coalesce(p_text, ''));
$$;

alter table public.usuarios
  drop column if exists role,
  drop column if exists pais_id;

alter table public.usuarios
  add column if not exists login_name text,
  add column if not exists login_password text,
  add column if not exists lamina_path text;

update public.usuarios
set
  name = public.strip_diacritics(name),
  login_name = public.strip_diacritics(coalesce(nullif(login_name, ''), name)),
  login_password = public.strip_diacritics(coalesce(nullif(login_password, ''), coalesce(nullif(login_name, ''), name))),
  lamina_path = public.strip_diacritics(coalesce(nullif(lamina_path, ''), ''))
where true;

alter table public.usuarios
  alter column login_name set not null,
  alter column login_password set not null,
  alter column lamina_path set not null,
  alter column lamina_path set default '';

create unique index if not exists idx_usuarios_login_name
  on public.usuarios (login_name);

create table if not exists public.figuritas (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.usuarios(id) on update cascade on delete cascade,
  foto_path text not null default '',
  created_at timestamptz not null default now()
);

create index if not exists idx_figuritas_user_id
  on public.figuritas (user_id);

create or replace function public.generate_secret_code(
  p_len integer default 8
)
returns text
language sql
set search_path = public
as $$
  select upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, greatest(4, p_len)));
$$;

alter table public.figuritas
  add column if not exists secret_code text;

drop view if exists public.codigos_sectretos;
drop view if exists public.codigos_secretos;

alter table public.figuritas
  drop column if exists secret_code_uses_total,
  drop column if exists secret_code_uses_remaining;

update public.figuritas
set secret_code = coalesce(nullif(secret_code, ''), public.generate_secret_code())
where true;

update public.figuritas
set foto_path = public.strip_diacritics(coalesce(nullif(foto_path, ''), ''))
where true;

alter table public.figuritas
  alter column secret_code set default public.generate_secret_code(),
  alter column secret_code set not null;

create unique index if not exists idx_figuritas_secret_code
  on public.figuritas (secret_code);

create or replace function public.configurar_codigo_secreto(
  p_figurita_id bigint,
  p_secret_code text default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_secret_code text;
begin
  select coalesce(nullif(secret_code, ''), public.generate_secret_code())
  into v_secret_code
  from public.figuritas
  where id = p_figurita_id;

  if not found then
    raise exception 'figurita no encontrada';
  end if;

  if trim(coalesce(p_secret_code, '')) <> '' then
    v_secret_code := trim(public.strip_diacritics(p_secret_code));
    if v_secret_code = '' then
      v_secret_code := public.generate_secret_code();
    end if;
  end if;

  update public.figuritas
  set secret_code = v_secret_code
  where id = p_figurita_id;
end;
$$;

create or replace view public.codigos_secretos as
select
  f.id as figurita_id,
  public.strip_diacritics(u.name) as nombre,
  f.secret_code
from public.figuritas f
join public.usuarios u on u.id = f.user_id;

create or replace view public.codigos_sectretos as
select *
from public.codigos_secretos;

create table if not exists public.validaciones_secretas (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.usuarios(id) on update cascade on delete cascade,
  figurita_id bigint not null references public.figuritas(id) on update cascade on delete cascade,
  status text not null default 'pending' check (status in ('pending', 'accepted', 'rejected', 'cancelled')),
  created_at timestamptz not null default now(),
  responded_at timestamptz,
  responded_by_user_id bigint references public.usuarios(id) on update cascade on delete set null
);

create index if not exists idx_validaciones_secretas_user_id
  on public.validaciones_secretas (user_id);

create index if not exists idx_validaciones_secretas_figurita_id
  on public.validaciones_secretas (figurita_id);

create index if not exists idx_validaciones_secretas_status
  on public.validaciones_secretas (status);

create unique index if not exists idx_validaciones_secretas_pending_unique
  on public.validaciones_secretas (user_id, figurita_id)
  where status = 'pending';

create table if not exists public.usuario_figuritas (
  user_id bigint not null references public.usuarios(id) on update cascade on delete cascade,
  figurita_id bigint not null references public.figuritas(id) on update cascade on delete cascade,
  cantidad integer not null default 0 check (cantidad >= 0),
  created_at timestamptz not null default now(),
  primary key (user_id, figurita_id)
);

create index if not exists idx_usuario_figuritas_figurita_id
  on public.usuario_figuritas (figurita_id);

create table if not exists public.intercambios (
  id bigint generated by default as identity primary key,
  from_user_id bigint not null references public.usuarios(id) on update cascade on delete cascade,
  to_user_id bigint not null references public.usuarios(id) on update cascade on delete cascade,
  msg text,
  status text not null default 'pending' check (status in ('pending', 'accepted', 'rejected', 'cancelled')),
  created_at timestamptz not null default now(),
  responded_at timestamptz
);

create index if not exists idx_intercambios_from_user_id
  on public.intercambios (from_user_id);

create index if not exists idx_intercambios_to_user_id
  on public.intercambios (to_user_id);

create index if not exists idx_intercambios_status
  on public.intercambios (status);

create table if not exists public.intercambio_items (
  id bigint generated by default as identity primary key,
  intercambio_id bigint not null references public.intercambios(id) on update cascade on delete cascade,
  figurita_id bigint not null references public.figuritas(id) on update cascade on delete cascade,
  side text not null check (side in ('offer', 'request')),
  created_at timestamptz not null default now(),
  unique (intercambio_id, side, figurita_id)
);

create index if not exists idx_intercambio_items_intercambio_id
  on public.intercambio_items (intercambio_id);

create index if not exists idx_intercambio_items_figurita_id
  on public.intercambio_items (figurita_id);

create table if not exists public.mensajes (
  id bigint generated by default as identity primary key,
  from_user_id bigint not null references public.usuarios(id) on update cascade on delete cascade,
  to_user_id bigint references public.usuarios(id) on update cascade on delete cascade,
  intercambio_id bigint references public.intercambios(id) on update cascade on delete cascade,
  body text not null,
  is_read boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists idx_mensajes_from_user_id
  on public.mensajes (from_user_id);

create index if not exists idx_mensajes_to_user_id
  on public.mensajes (to_user_id);

create index if not exists idx_mensajes_intercambio_id
  on public.mensajes (intercambio_id);

create table if not exists public.comentarios (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.usuarios(id) on update cascade on delete cascade,
  figurita_id bigint references public.figuritas(id) on update cascade on delete cascade,
  intercambio_id bigint references public.intercambios(id) on update cascade on delete cascade,
  body text not null,
  created_at timestamptz not null default now(),
  constraint comentarios_target_check check (
    (figurita_id is not null and intercambio_id is null)
    or
    (figurita_id is null and intercambio_id is not null)
  )
);

create index if not exists idx_comentarios_user_id
  on public.comentarios (user_id);

create index if not exists idx_comentarios_figurita_id
  on public.comentarios (figurita_id);

create index if not exists idx_comentarios_intercambio_id
  on public.comentarios (intercambio_id);

create or replace function public.set_usuario_figurita_qty(
  p_user_id bigint,
  p_figurita_id bigint,
  p_qty integer
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if p_qty < 0 then
    raise exception 'cantidad invalida';
  end if;

  if p_qty = 0 then
    delete from public.usuario_figuritas
    where user_id = p_user_id
      and figurita_id = p_figurita_id;
    return;
  end if;

  insert into public.usuario_figuritas (user_id, figurita_id, cantidad, created_at)
  values (p_user_id, p_figurita_id, p_qty, now())
  on conflict (user_id, figurita_id)
  do update set
    cantidad = excluded.cantidad,
    created_at = now();
end;
$$;

create or replace function public.activar_figurita_con_codigo(
  p_user_id bigint,
  p_figurita_id bigint,
  p_codigo text
)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  v_secret text;
  v_has_pending boolean;
begin
  select f.secret_code
  into v_secret
  from public.figuritas f
  where f.id = p_figurita_id;

  if not found then
    raise exception 'figurita no encontrada';
  end if;

  if upper(regexp_replace(coalesce(v_secret, ''), '[^A-Za-z0-9]', '', 'g')) <>
     upper(regexp_replace(coalesce(p_codigo, ''), '[^A-Za-z0-9]', '', 'g')) then
    raise exception 'codigo incorrecto';
  end if;

  select exists(
    select 1
    from public.validaciones_secretas
    where user_id = p_user_id
      and figurita_id = p_figurita_id
      and status = 'pending'
  )
  into v_has_pending;

  if v_has_pending then
    raise exception 'ya pendiente';
  end if;

  insert into public.validaciones_secretas (
    user_id,
    figurita_id,
    status,
    created_at
  )
  values (
    p_user_id,
    p_figurita_id,
    'pending',
    now()
  );

  return 'pending';
end;
$$;

create or replace function public.aprobar_validacion_secreta(
  p_validacion_id bigint,
  p_approved_by_user_id bigint default null
)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  v_validacion record;
  v_lamina_path text;
begin
  select *
  into v_validacion
  from public.validaciones_secretas
  where id = p_validacion_id
  for update;

  if not found then
    raise exception 'validacion no encontrada';
  end if;

  if v_validacion.status <> 'pending' then
    raise exception 'validacion ya procesada';
  end if;

  select coalesce(u.lamina_path, '')
  into v_lamina_path
  from public.figuritas f
  join public.usuarios u on u.id = f.user_id
  where f.id = v_validacion.figurita_id;

  if coalesce(v_lamina_path, '') <> '' then
    update public.figuritas
    set foto_path = coalesce(nullif(foto_path, ''), public.strip_diacritics(v_lamina_path))
    where id = v_validacion.figurita_id;
  end if;

  insert into public.usuario_figuritas as uf (user_id, figurita_id, cantidad, created_at)
  values (v_validacion.user_id, v_validacion.figurita_id, 1, now())
  on conflict (user_id, figurita_id)
  do update set
    cantidad = uf.cantidad + excluded.cantidad,
    created_at = now();

  update public.validaciones_secretas
  set status = 'accepted',
      responded_at = now(),
      responded_by_user_id = p_approved_by_user_id
  where id = p_validacion_id;

  return 'accepted';
end;
$$;

create or replace function public.listar_usuario_figuritas()
returns table (
  user_id bigint,
  figurita_id bigint,
  cantidad integer,
  created_at timestamptz
)
language sql
security definer
set search_path = public
as $$
  select
    uf.user_id,
    uf.figurita_id,
    uf.cantidad,
    uf.created_at
  from public.usuario_figuritas uf
  order by uf.created_at asc, uf.user_id asc, uf.figurita_id asc;
$$;

create or replace function public.listar_usuario_figuritas_por_usuario(
  p_user_id bigint
)
returns table (
  user_id bigint,
  figurita_id bigint,
  cantidad integer,
  created_at timestamptz
)
language sql
security definer
set search_path = public
as $$
  select
    uf.user_id,
    uf.figurita_id,
    uf.cantidad,
    uf.created_at
  from public.usuario_figuritas uf
  where uf.user_id = p_user_id
  order by uf.created_at asc, uf.user_id asc, uf.figurita_id asc;
$$;

create or replace function public.listar_resumen_usuario_figuritas()
returns table (
  user_id bigint,
  figuritas_distintas integer
)
language sql
security definer
set search_path = public
as $$
  select
    uf.user_id,
    count(*)::integer as figuritas_distintas
  from public.usuario_figuritas uf
  where uf.cantidad > 0
  group by uf.user_id
  order by uf.user_id asc;
$$;

create or replace function public.listar_validaciones_secretas_pendientes()
returns table (
  id bigint,
  user_id bigint,
  figurita_id bigint,
  status text,
  created_at timestamptz,
  responded_at timestamptz,
  responded_by_user_id bigint
)
language sql
security definer
set search_path = public
as $$
  select
    vs.id,
    vs.user_id,
    vs.figurita_id,
    vs.status,
    vs.created_at,
    vs.responded_at,
    vs.responded_by_user_id
  from public.validaciones_secretas vs
  where vs.status = 'pending'
  order by vs.created_at asc, vs.id asc;
$$;

create or replace function public.rechazar_validacion_secreta(
  p_validacion_id bigint,
  p_approved_by_user_id bigint default null
)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  v_validacion record;
begin
  select *
  into v_validacion
  from public.validaciones_secretas
  where id = p_validacion_id
  for update;

  if not found then
    raise exception 'validacion no encontrada';
  end if;

  if v_validacion.status <> 'pending' then
    raise exception 'validacion ya procesada';
  end if;

  update public.validaciones_secretas
  set status = 'rejected',
      responded_at = now(),
      responded_by_user_id = p_approved_by_user_id
  where id = p_validacion_id;

  return 'rejected';
end;
$$;

create or replace function public.crear_intercambio(
  p_from_user_id bigint,
  p_to_user_id bigint,
  p_msg text default null,
  p_offer_ids bigint[] default '{}'::bigint[],
  p_request_ids bigint[] default '{}'::bigint[]
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_intercambio_id bigint;
  v_figid bigint;
  v_blocked_offer_ids bigint[];
begin
  perform 1
  from public.usuarios
  where id = p_from_user_id
  for update;

  select coalesce(array_agg(distinct offered.fig_id), '{}'::bigint[])
  into v_blocked_offer_ids
  from unnest(coalesce(p_offer_ids, '{}'::bigint[])) as offered(fig_id)
  where exists (
    select 1
    from public.intercambios i
    join public.intercambio_items ii on ii.intercambio_id = i.id
    where i.from_user_id = p_from_user_id
      and i.status = 'pending'
      and ii.side = 'offer'
      and ii.figurita_id = offered.fig_id
  );

  if array_length(v_blocked_offer_ids, 1) is not null then
    raise exception 'figurita ya comprometida en intercambio pendiente';
  end if;

  insert into public.intercambios (from_user_id, to_user_id, msg, status, created_at)
  values (p_from_user_id, p_to_user_id, p_msg, 'pending', now())
  returning id into v_intercambio_id;

  foreach v_figid in array coalesce(p_offer_ids, '{}'::bigint[]) loop
    insert into public.intercambio_items (intercambio_id, figurita_id, side, created_at)
    values (v_intercambio_id, v_figid, 'offer', now());
  end loop;

  foreach v_figid in array coalesce(p_request_ids, '{}'::bigint[]) loop
    insert into public.intercambio_items (intercambio_id, figurita_id, side, created_at)
    values (v_intercambio_id, v_figid, 'request', now());
  end loop;

  return v_intercambio_id;
end;
$$;

create or replace function public.responder_intercambio(
  p_intercambio_id bigint,
  p_status text
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_trade record;
  v_figid bigint;
  v_qty integer;
  v_offer bigint[];
  v_request bigint[];
begin
  select *
  into v_trade
  from public.intercambios
  where id = p_intercambio_id
  for update;

  if not found then
    raise exception 'intercambio no encontrado';
  end if;

  if v_trade.status <> 'pending' then
    raise exception 'intercambio ya procesado';
  end if;

  if p_status not in ('accepted', 'rejected', 'cancelled') then
    raise exception 'estado invalido';
  end if;

  if p_status = 'accepted' then
    select coalesce(array_agg(figurita_id), '{}'::bigint[])
    into v_offer
    from public.intercambio_items
    where intercambio_id = p_intercambio_id
      and side = 'offer';

    select coalesce(array_agg(figurita_id), '{}'::bigint[])
    into v_request
    from public.intercambio_items
    where intercambio_id = p_intercambio_id
      and side = 'request';

    foreach v_figid in array coalesce(v_offer, '{}'::bigint[]) loop
      select cantidad
      into v_qty
      from public.usuario_figuritas
      where user_id = v_trade.from_user_id
        and figurita_id = v_figid;

      if coalesce(v_qty, 0) <= 0 then
        raise exception 'figuritas insuficientes para aceptar el intercambio';
      end if;

      perform public.set_usuario_figurita_qty(v_trade.from_user_id, v_figid, v_qty - 1);
      select cantidad into v_qty
      from public.usuario_figuritas
      where user_id = v_trade.to_user_id
        and figurita_id = v_figid;
      perform public.set_usuario_figurita_qty(v_trade.to_user_id, v_figid, coalesce(v_qty, 0) + 1);
    end loop;

    foreach v_figid in array coalesce(v_request, '{}'::bigint[]) loop
      select cantidad
      into v_qty
      from public.usuario_figuritas
      where user_id = v_trade.to_user_id
        and figurita_id = v_figid;

      if coalesce(v_qty, 0) <= 0 then
        raise exception 'figuritas insuficientes para aceptar el intercambio';
      end if;

      perform public.set_usuario_figurita_qty(v_trade.to_user_id, v_figid, v_qty - 1);
      select cantidad into v_qty
      from public.usuario_figuritas
      where user_id = v_trade.from_user_id
        and figurita_id = v_figid;
      perform public.set_usuario_figurita_qty(v_trade.from_user_id, v_figid, coalesce(v_qty, 0) + 1);
    end loop;
  end if;

  update public.intercambios
  set status = p_status,
      responded_at = now()
  where id = p_intercambio_id;
end;
$$;

create or replace function public.crear_mensaje(
  p_from_user_id bigint,
  p_to_user_id bigint,
  p_body text,
  p_intercambio_id bigint default null
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_id bigint;
begin
  insert into public.mensajes (from_user_id, to_user_id, intercambio_id, body, is_read, created_at)
  values (p_from_user_id, p_to_user_id, p_intercambio_id, p_body, false, now())
  returning id into v_id;

  return v_id;
end;
$$;

create or replace function public.crear_comentario(
  p_user_id bigint,
  p_body text,
  p_figurita_id bigint default null,
  p_intercambio_id bigint default null
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_id bigint;
begin
  if (p_figurita_id is null and p_intercambio_id is null)
    or (p_figurita_id is not null and p_intercambio_id is not null) then
    raise exception 'comentario sin objetivo valido';
  end if;

  insert into public.comentarios (user_id, figurita_id, intercambio_id, body, created_at)
  values (p_user_id, p_figurita_id, p_intercambio_id, p_body, now())
  returning id into v_id;

  return v_id;
end;
$$;

create or replace function public.marcar_mensajes_leidos(
  p_user_id bigint
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.mensajes
  set is_read = true
  where to_user_id = p_user_id
    and is_read = false;
end;
$$;

grant usage on schema public to anon, authenticated;
revoke select on public.figuritas from anon, authenticated;
grant select (id, user_id, foto_path, created_at) on public.figuritas to anon, authenticated;
grant select on public.codigos_secretos to anon, authenticated;
grant select on public.codigos_sectretos to anon, authenticated;
grant select on public.validaciones_secretas to anon, authenticated;
grant select on public.usuarios, public.figuritas, public.usuario_figuritas, public.intercambios, public.intercambio_items, public.mensajes, public.comentarios to anon, authenticated;
grant execute on function public.listar_usuario_figuritas() to anon, authenticated;
grant execute on function public.listar_usuario_figuritas_por_usuario(bigint) to anon, authenticated;
grant execute on function public.listar_resumen_usuario_figuritas() to anon, authenticated;
grant execute on function public.listar_validaciones_secretas_pendientes() to anon, authenticated;
grant execute on function public.set_usuario_figurita_qty(bigint, bigint, integer) to anon, authenticated;
grant execute on function public.activar_figurita_con_codigo(bigint, bigint, text) to anon, authenticated;
grant execute on function public.aprobar_validacion_secreta(bigint, bigint) to anon, authenticated;
grant execute on function public.rechazar_validacion_secreta(bigint, bigint) to anon, authenticated;
grant execute on function public.crear_intercambio(bigint, bigint, text, bigint[], bigint[]) to anon, authenticated;
grant execute on function public.responder_intercambio(bigint, text) to anon, authenticated;
grant execute on function public.crear_mensaje(bigint, bigint, text, bigint) to anon, authenticated;
grant execute on function public.crear_comentario(bigint, text, bigint, bigint) to anon, authenticated;
grant execute on function public.marcar_mensajes_leidos(bigint) to anon, authenticated;
