-- Auto-generated from laminas/*.png
-- Run this after db/schema.sql.

insert into public.usuarios (id, name, login_name, login_password, lamina_path) values
  (1, 'Abrahamzick Orozco', 'Abrahamzick Orozco', 'Abrahamzick Orozco', 'laminas/Abrahamzick Orozco.png'),
  (2, 'Adrian Sepulveda', 'Adrian Sepulveda', 'Adrian Sepulveda', 'laminas/Adrian Sepulveda.png'),
  (3, 'Adriana Celis', 'Adriana Celis', 'Adriana Celis', 'laminas/Adriana Celis.png'),
  (4, 'Alberto Bachler', 'Alberto Bachler', 'Alberto Bachler', 'laminas/Alberto Bachler.png'),
  (5, 'Aldo Ayala', 'Aldo Ayala', 'Aldo Ayala', 'laminas/Aldo Ayala.png'),
  (6, 'Alejandro Albertz', 'Alejandro Albertz', 'Alejandro Albertz', 'laminas/Alejandro Albertz.png'),
  (7, 'Alejandro Gonzalez', 'Alejandro Gonzalez', 'Alejandro Gonzalez', 'laminas/Alejandro Gonzalez.png'),
  (8, 'Alexis Bustamante', 'Alexis Bustamante', 'Alexis Bustamante', 'laminas/Alexis Bustamante.png'),
  (9, 'Alvaro Bueno', 'Alvaro Bueno', 'Alvaro Bueno', 'laminas/Alvaro Bueno.png'),
  (10, 'Andres Ordonez', 'Andres Ordonez', 'Andres Ordonez', 'laminas/Andres Ordonez.png'),
  (11, 'Andres Osorio', 'Andres Osorio', 'Andres Osorio', 'laminas/Andres Osorio.png'),
  (12, 'Andres Quiero', 'Andres Quiero', 'Andres Quiero', 'laminas/Andres Quiero.png'),
  (13, 'Andres Tolosa', 'Andres Tolosa', 'Andres Tolosa', 'laminas/Andres Tolosa.png'),
  (14, 'Angel Castillo', 'Angel Castillo', 'Angel Castillo', 'laminas/Angel Castillo.png'),
  (15, 'Angel Ruggia', 'Angel Ruggia', 'Angel Ruggia', 'laminas/Angel Ruggia.png'),
  (16, 'Angela Sierra', 'Angela Sierra', 'Angela Sierra', 'laminas/Angela Sierra.png'),
  (17, 'Angie Callejas', 'Angie Callejas', 'Angie Callejas', 'laminas/Angie Callejas.png'),
  (18, 'Antonella Gomez', 'Antonella Gomez', 'Antonella Gomez', 'laminas/Antonella Gomez.png'),
  (19, 'Ariadna Flores', 'Ariadna Flores', 'Ariadna Flores', 'laminas/Ariadna Flores.png'),
  (20, 'Ariel Gringaus', 'Ariel Gringaus', 'Ariel Gringaus', 'laminas/Ariel Gringaus.png'),
  (21, 'Ariel Rojas', 'Ariel Rojas', 'Ariel Rojas', 'laminas/Ariel Rojas.png'),
  (22, 'Arnoldo Chazeau', 'Arnoldo Chazeau', 'Arnoldo Chazeau', 'laminas/Arnoldo Chazeau.png'),
  (23, 'Arturo Rincon', 'Arturo Rincon', 'Arturo Rincon', 'laminas/Arturo Rincon.png'),
  (24, 'Ashly Flores', 'Ashly Flores', 'Ashly Flores', 'laminas/Ashly Flores.png'),
  (25, 'Aymara Martinez', 'Aymara Martinez', 'Aymara Martinez', 'laminas/Aymara Martinez.png'),
  (26, 'Bastian Vallejos', 'Bastian Vallejos', 'Bastian Vallejos', 'laminas/Bastian Vallejos.png'),
  (27, 'Belen Avila', 'Belen Avila', 'Belen Avila', 'laminas/Belen Avila.png'),
  (28, 'Brenda Aquino', 'Brenda Aquino', 'Brenda Aquino', 'laminas/Brenda Aquino.png'),
  (29, 'Camila Casanova', 'Camila Casanova', 'Camila Casanova', 'laminas/Camila Casanova.png'),
  (30, 'Carlos Rodriguez', 'Carlos Rodriguez', 'Carlos Rodriguez', 'laminas/Carlos Rodriguez.png'),
  (31, 'Carlos Vega', 'Carlos Vega', 'Carlos Vega', 'laminas/Carlos Vega.png'),
  (32, 'Carolina Araya', 'Carolina Araya', 'Carolina Araya', 'laminas/Carolina Araya.png'),
  (33, 'Catalina Fuentealba', 'Catalina Fuentealba', 'Catalina Fuentealba', 'laminas/Catalina Fuentealba.png'),
  (34, 'Catalina Mantilla', 'Catalina Mantilla', 'Catalina Mantilla', 'laminas/Catalina Mantilla.png'),
  (35, 'Cesar Matheus', 'Cesar Matheus', 'Cesar Matheus', 'laminas/Cesar Matheus.png'),
  (36, 'Cristian Henriquez', 'Cristian Henriquez', 'Cristian Henriquez', 'laminas/Cristian Henriquez.png'),
  (37, 'Cristian Noguera', 'Cristian Noguera', 'Cristian Noguera', 'laminas/Cristian Noguera.png'),
  (38, 'Cristian Zapata', 'Cristian Zapata', 'Cristian Zapata', 'laminas/Cristian Zapata.png'),
  (39, 'Cristina Molina', 'Cristina Molina', 'Cristina Molina', 'laminas/Cristina Molina.png'),
  (40, 'Cynthia Marchant', 'Cynthia Marchant', 'Cynthia Marchant', 'laminas/Cynthia Marchant.png'),
  (41, 'Daniel Medina', 'Daniel Medina', 'Daniel Medina', 'laminas/Daniel Medina.png'),
  (42, 'Daniela Parra', 'Daniela Parra', 'Daniela Parra', 'laminas/Daniela Parra.png'),
  (43, 'David Barreda', 'David Barreda', 'David Barreda', 'laminas/David Barreda.png'),
  (44, 'David Guarin', 'David Guarin', 'David Guarin', 'laminas/David Guarin.png'),
  (45, 'Derly Florez', 'Derly Florez', 'Derly Florez', 'laminas/Derly Florez.png'),
  (46, 'Diana Sandoval', 'Diana Sandoval', 'Diana Sandoval', 'laminas/Diana Sandoval.png'),
  (47, 'Edward Henao', 'Edward Henao', 'Edward Henao', 'laminas/Edward Henao.png'),
  (48, 'Esteban Aguirre', 'Esteban Aguirre', 'Esteban Aguirre', 'laminas/Esteban Aguirre.png'),
  (49, 'Evelyn Espejo', 'Evelyn Espejo', 'Evelyn Espejo', 'laminas/Evelyn Espejo.png'),
  (50, 'Ezequiel Balasch', 'Ezequiel Balasch', 'Ezequiel Balasch', 'laminas/Ezequiel Balasch.png'),
  (51, 'Felipe Miranda', 'Felipe Miranda', 'Felipe Miranda', 'laminas/Felipe Miranda.png'),
  (52, 'Felipe Weiss', 'Felipe Weiss', 'Felipe Weiss', 'laminas/Felipe Weiss.png'),
  (53, 'Fernanda Florez', 'Fernanda Florez', 'Fernanda Florez', 'laminas/Fernanda Florez.png'),
  (54, 'Francisca Soto', 'Francisca Soto', 'Francisca Soto', 'laminas/Francisca Soto.png'),
  (55, 'Gabriela Jugo', 'Gabriela Jugo', 'Gabriela Jugo', 'laminas/Gabriela Jugo.png'),
  (56, 'Genito Andrade', 'Genito Andrade', 'Genito Andrade', 'laminas/Genito Andrade.png'),
  (57, 'Gerardo Barragan', 'Gerardo Barragan', 'Gerardo Barragan', 'laminas/Gerardo Barragan.png'),
  (58, 'Gonzalo Bertomeu', 'Gonzalo Bertomeu', 'Gonzalo Bertomeu', 'laminas/Gonzalo Bertomeu.png'),
  (59, 'Gonzalo de la Jara', 'Gonzalo de la Jara', 'Gonzalo de la Jara', 'laminas/Gonzalo de la Jara.png'),
  (60, 'Gonzalo Lopez', 'Gonzalo Lopez', 'Gonzalo Lopez', 'laminas/Gonzalo Lopez.png'),
  (61, 'Hector Rojo', 'Hector Rojo', 'Hector Rojo', 'laminas/Hector Rojo.png'),
  (62, 'Ignacio Portilla', 'Ignacio Portilla', 'Ignacio Portilla', 'laminas/Ignacio Portilla.png'),
  (63, 'Israel Flores', 'Israel Flores', 'Israel Flores', 'laminas/Israel Flores.png'),
  (64, 'Jaime Herreros', 'Jaime Herreros', 'Jaime Herreros', 'laminas/Jaime Herreros.png'),
  (65, 'Javier Espinoza', 'Javier Espinoza', 'Javier Espinoza', 'laminas/Javier Espinoza.png'),
  (66, 'Javier Fonseca', 'Javier Fonseca', 'Javier Fonseca', 'laminas/Javier Fonseca.png'),
  (67, 'Javiera Huentemil', 'Javiera Huentemil', 'Javiera Huentemil', 'laminas/Javiera Huentemil.png'),
  (68, 'Jeison Jimenez', 'Jeison Jimenez', 'Jeison Jimenez', 'laminas/Jeison Jimenez.png'),
  (69, 'Jennifer Luengas', 'Jennifer Luengas', 'Jennifer Luengas', 'laminas/Jennifer Luengas.png'),
  (70, 'Jesus Osorio', 'Jesus Osorio', 'Jesus Osorio', 'laminas/Jesus Osorio.png'),
  (71, 'Johan Casanova', 'Johan Casanova', 'Johan Casanova', 'laminas/Johan Casanova.png'),
  (72, 'Johan Rosas', 'Johan Rosas', 'Johan Rosas', 'laminas/Johan Rosas.png'),
  (73, 'Jonathan Sepulveda', 'Jonathan Sepulveda', 'Jonathan Sepulveda', 'laminas/Jonathan Sepulveda.png'),
  (74, 'Jorge Reynoso', 'Jorge Reynoso', 'Jorge Reynoso', 'laminas/Jorge Reynoso.png'),
  (75, 'Jose Manuel Barros', 'Jose Manuel Barros', 'Jose Manuel Barros', 'laminas/Jose Manuel Barros.png'),
  (76, 'Jose Matus', 'Jose Matus', 'Jose Matus', 'laminas/Jose Matus.png'),
  (77, 'Jose Miguel Moreno', 'Jose Miguel Moreno', 'Jose Miguel Moreno', 'laminas/Jose Miguel Moreno.png'),
  (78, 'Jose Romero', 'Jose Romero', 'Jose Romero', 'laminas/Jose Romero.png'),
  (79, 'Juan David Loaiza', 'Juan David Loaiza', 'Juan David Loaiza', 'laminas/Juan David Loaiza.png'),
  (80, 'Juan Ignacio Castro', 'Juan Ignacio Castro', 'Juan Ignacio Castro', 'laminas/Juan Ignacio Castro.png'),
  (81, 'Juan Manuel Zuniga', 'Juan Manuel Zuniga', 'Juan Manuel Zuniga', 'laminas/Juan Manuel Zuniga.png'),
  (82, 'Juan Sebastian Illera', 'Juan Sebastian Illera', 'Juan Sebastian Illera', 'laminas/Juan Sebastian Illera.png'),
  (83, 'Juan Sebastian Silva', 'Juan Sebastian Silva', 'Juan Sebastian Silva', 'laminas/Juan Sebastian Silva.png'),
  (84, 'Juliana Daza', 'Juliana Daza', 'Juliana Daza', 'laminas/Juliana Daza.png'),
  (85, 'Julieth Watson', 'Julieth Watson', 'Julieth Watson', 'laminas/Julieth Watson.png'),
  (86, 'Karina Norambuena', 'Karina Norambuena', 'Karina Norambuena', 'laminas/Karina Norambuena.png'),
  (87, 'Karol Rodriguez', 'Karol Rodriguez', 'Karol Rodriguez', 'laminas/Karol Rodriguez.png'),
  (88, 'Katherin Bustos', 'Katherin Bustos', 'Katherin Bustos', 'laminas/Katherin Bustos.png'),
  (89, 'Kathy Figueroa', 'Kathy Figueroa', 'Kathy Figueroa', 'laminas/Kathy Figueroa.png'),
  (90, 'Laura Hurtado', 'Laura Hurtado', 'Laura Hurtado', 'laminas/Laura Hurtado.png'),
  (91, 'Leonardo Revilla', 'Leonardo Revilla', 'Leonardo Revilla', 'laminas/Leonardo Revilla.png'),
  (92, 'Liliana Jimenez', 'Liliana Jimenez', 'Liliana Jimenez', 'laminas/Liliana Jimenez.png'),
  (93, 'Liliana Martinez', 'Liliana Martinez', 'Liliana Martinez', 'laminas/Liliana Martinez.png'),
  (94, 'Lorena Silva', 'Lorena Silva', 'Lorena Silva', 'laminas/Lorena Silva.png'),
  (95, 'Luis Cova', 'Luis Cova', 'Luis Cova', 'laminas/Luis Cova.png'),
  (96, 'Luisa Aravena', 'Luisa Aravena', 'Luisa Aravena', 'laminas/Luisa Aravena.png'),
  (97, 'Maira Bello', 'Maira Bello', 'Maira Bello', 'laminas/Maira Bello.png'),
  (98, 'Manuel Hernandez', 'Manuel Hernandez', 'Manuel Hernandez', 'laminas/Manuel Hernandez.png'),
  (99, 'Manuel Lamas', 'Manuel Lamas', 'Manuel Lamas', 'laminas/Manuel Lamas.png'),
  (100, 'Marcela Garzon', 'Marcela Garzon', 'Marcela Garzon', 'laminas/Marcela Garzon.png'),
  (101, 'Marcos Butala', 'Marcos Butala', 'Marcos Butala', 'laminas/Marcos Butala.png'),
  (102, 'Maria Cecilia Calderini', 'Maria Cecilia Calderini', 'Maria Cecilia Calderini', 'laminas/Maria Cecilia Calderini.png'),
  (103, 'Maria de los Angeles Pino', 'Maria de los Angeles Pino', 'Maria de los Angeles Pino', 'laminas/Maria de los Angeles Pino.png'),
  (104, 'Maria Fernanda Diaz', 'Maria Fernanda Diaz', 'Maria Fernanda Diaz', 'laminas/Maria Fernanda Diaz.png'),
  (105, 'Maria Jose Maray', 'Maria Jose Maray', 'Maria Jose Maray', 'laminas/Maria Jose Maray.png'),
  (106, 'Marialy Torrealba', 'Marialy Torrealba', 'Marialy Torrealba', 'laminas/Marialy Torrealba.png'),
  (107, 'Mariela Cuahutencos', 'Mariela Cuahutencos', 'Mariela Cuahutencos', 'laminas/Mariela Cuahutencos.png'),
  (108, 'Mariom Soto', 'Mariom Soto', 'Mariom Soto', 'laminas/Mariom Soto.png'),
  (109, 'Marlen Arriagada', 'Marlen Arriagada', 'Marlen Arriagada', 'laminas/Marlen Arriagada.png'),
  (110, 'Martin Gonzalez', 'Martin Gonzalez', 'Martin Gonzalez', 'laminas/Martin Gonzalez.png'),
  (111, 'Martin Sztajn', 'Martin Sztajn', 'Martin Sztajn', 'laminas/Martin Sztajn.png'),
  (112, 'Matt Deacon', 'Matt Deacon', 'Matt Deacon', 'laminas/Matt Deacon.png'),
  (113, 'Mauricio Bustamante', 'Mauricio Bustamante', 'Mauricio Bustamante', 'laminas/Mauricio Bustamante.png'),
  (114, 'Melanie Galuschka', 'Melanie Galuschka', 'Melanie Galuschka', 'laminas/Melanie Galuschka.png'),
  (115, 'Melissa Calderon', 'Melissa Calderon', 'Melissa Calderon', 'laminas/Melissa Calderon.png'),
  (116, 'Mini Arevalo', 'Mini Arevalo', 'Mini Arevalo', 'laminas/Mini Arevalo.png'),
  (117, 'Natali Rodriguez', 'Natali Rodriguez', 'Natali Rodriguez', 'laminas/Natali Rodriguez.png'),
  (118, 'Natalia Cancino', 'Natalia Cancino', 'Natalia Cancino', 'laminas/Natalia Cancino.png'),
  (119, 'Natalia Chandia', 'Natalia Chandia', 'Natalia Chandia', 'laminas/Natalia Chandia.png'),
  (120, 'Natalia Imazio', 'Natalia Imazio', 'Natalia Imazio', 'laminas/Natalia Imazio.png'),
  (121, 'Natalia Vidal', 'Natalia Vidal', 'Natalia Vidal', 'laminas/Natalia Vidal.png'),
  (122, 'Nataly Salinas', 'Nataly Salinas', 'Nataly Salinas', 'laminas/Nataly Salinas.png'),
  (123, 'Olga Torres', 'Olga Torres', 'Olga Torres', 'laminas/Olga Torres.png'),
  (124, 'Orlando Vazquez', 'Orlando Vazquez', 'Orlando Vazquez', 'laminas/Orlando Vazquez.png'),
  (125, 'Pablo Delillo', 'Pablo Delillo', 'Pablo Delillo', 'laminas/Pablo Delillo.png'),
  (126, 'Pablo Ormero', 'Pablo Ormero', 'Pablo Ormero', 'laminas/Pablo Ormero.png'),
  (127, 'Paola Melo', 'Paola Melo', 'Paola Melo', 'laminas/Paola Melo.png'),
  (128, 'Patricio Aliaga', 'Patricio Aliaga', 'Patricio Aliaga', 'laminas/Patricio Aliaga.png'),
  (129, 'Paula Pizarro', 'Paula Pizarro', 'Paula Pizarro', 'laminas/Paula Pizarro.png'),
  (130, 'Paulina Caceres', 'Paulina Caceres', 'Paulina Caceres', 'laminas/Paulina Caceres.png'),
  (131, 'Pilar Castillo', 'Pilar Castillo', 'Pilar Castillo', 'laminas/Pilar Castillo.png'),
  (132, 'Renzo Gola', 'Renzo Gola', 'Renzo Gola', 'laminas/Renzo Gola.png'),
  (133, 'Ricardo Vargas', 'Ricardo Vargas', 'Ricardo Vargas', 'laminas/Ricardo Vargas.png'),
  (134, 'Robert Gutierrez', 'Robert Gutierrez', 'Robert Gutierrez', 'laminas/Robert Gutierrez.png'),
  (135, 'Roberto Catalan', 'Roberto Catalan', 'Roberto Catalan', 'laminas/Roberto Catalan.png'),
  (136, 'Rodrigo Lerzundi', 'Rodrigo Lerzundi', 'Rodrigo Lerzundi', 'laminas/Rodrigo Lerzundi.png'),
  (137, 'Rodrigo Marambio', 'Rodrigo Marambio', 'Rodrigo Marambio', 'laminas/Rodrigo Marambio.png'),
  (138, 'Rodrigo Sepulveda', 'Rodrigo Sepulveda', 'Rodrigo Sepulveda', 'laminas/Rodrigo Sepulveda.png'),
  (139, 'Romina Lugo', 'Romina Lugo', 'Romina Lugo', 'laminas/Romina Lugo.png'),
  (140, 'Ruben Giraldo', 'Ruben Giraldo', 'Ruben Giraldo', 'laminas/Ruben Giraldo.png'),
  (141, 'Santiago Saavedra', 'Santiago Saavedra', 'Santiago Saavedra', 'laminas/Santiago Saavedra.png'),
  (142, 'Saul Ponce', 'Saul Ponce', 'Saul Ponce', 'laminas/Saul Ponce.png'),
  (143, 'Sebastian Maureira', 'Sebastian Maureira', 'Sebastian Maureira', 'laminas/Sebastian Maureira.png'),
  (144, 'Sebastian Riquelme', 'Sebastian Riquelme', 'Sebastian Riquelme', 'laminas/Sebastian Riquelme.png'),
  (145, 'Sergio Carrasco', 'Sergio Carrasco', 'Sergio Carrasco', 'laminas/Sergio Carrasco.png'),
  (146, 'Steven Arias', 'Steven Arias', 'Steven Arias', 'laminas/Steven Arias.png'),
  (147, 'Sussane Henriquez', 'Sussane Henriquez', 'Sussane Henriquez', 'laminas/Sussane Henriquez.png'),
  (148, 'Tatiana Torres', 'Tatiana Torres', 'Tatiana Torres', 'laminas/Tatiana Torres.png'),
  (149, 'Valentin Marchant', 'Valentin Marchant', 'Valentin Marchant', 'laminas/Valentin Marchant.png'),
  (150, 'Valeria Gonzalez', 'Valeria Gonzalez', 'Valeria Gonzalez', 'laminas/Valeria Gonzalez.png'),
  (151, 'Valeska Rivera', 'Valeska Rivera', 'Valeska Rivera', 'laminas/Valeska Rivera.png'),
  (152, 'Victor Bentiboglio', 'Victor Bentiboglio', 'Victor Bentiboglio', 'laminas/Victor Bentiboglio.png'),
  (153, 'Victor Gajardo', 'Victor Gajardo', 'Victor Gajardo', 'laminas/Victor Gajardo.png'),
  (154, 'William Guzman', 'William Guzman', 'William Guzman', 'laminas/William Guzman.png'),
  (155, 'Wolfran Pinzon', 'Wolfran Pinzon', 'Wolfran Pinzon', 'laminas/Wolfran Pinzon.png'),
  (156, 'Yeferson Gomez', 'Yeferson Gomez', 'Yeferson Gomez', 'laminas/Yeferson Gomez.png'),
  (157, 'Rocky', 'Rocky', 'Rocky', 'laminas/Rocky.png'),
  (158, 'Robotito', 'Robotito', 'Robotito', 'laminas/Robotito.png'),
  (159, 'Julio Iglesias', 'Julio Iglesias', 'Julio Iglesias', 'laminas/Julio Iglesias.png'),
  (160, 'Elias Lescano', 'Elias Lescano', 'Elias Lescano', 'laminas/Elias Lescano.png')
on conflict (id) do update set
  name = excluded.name,
  login_name = excluded.login_name,
  login_password = excluded.login_password,
  lamina_path = excluded.lamina_path;

insert into public.figuritas (id, user_id, foto_path) values
  (1, 1, 'laminas/Abrahamzick Orozco.png'),
  (2, 2, 'laminas/Adrian Sepulveda.png'),
  (3, 3, 'laminas/Adriana Celis.png'),
  (4, 4, 'laminas/Alberto Bachler.png'),
  (5, 5, 'laminas/Aldo Ayala.png'),
  (6, 6, 'laminas/Alejandro Albertz.png'),
  (7, 7, 'laminas/Alejandro Gonzalez.png'),
  (8, 8, 'laminas/Alexis Bustamante.png'),
  (9, 9, 'laminas/Alvaro Bueno.png'),
  (10, 10, 'laminas/Andres Ordonez.png'),
  (11, 11, 'laminas/Andres Osorio.png'),
  (12, 12, 'laminas/Andres Quiero.png'),
  (13, 13, 'laminas/Andres Tolosa.png'),
  (14, 14, 'laminas/Angel Castillo.png'),
  (15, 15, 'laminas/Angel Ruggia.png'),
  (16, 16, 'laminas/Angela Sierra.png'),
  (17, 17, 'laminas/Angie Callejas.png'),
  (18, 18, 'laminas/Antonella Gomez.png'),
  (19, 19, 'laminas/Ariadna Flores.png'),
  (20, 20, 'laminas/Ariel Gringaus.png'),
  (21, 21, 'laminas/Ariel Rojas.png'),
  (22, 22, 'laminas/Arnoldo Chazeau.png'),
  (23, 23, 'laminas/Arturo Rincon.png'),
  (24, 24, 'laminas/Ashly Flores.png'),
  (25, 25, 'laminas/Aymara Martinez.png'),
  (26, 26, 'laminas/Bastian Vallejos.png'),
  (27, 27, 'laminas/Belen Avila.png'),
  (28, 28, 'laminas/Brenda Aquino.png'),
  (29, 29, 'laminas/Camila Casanova.png'),
  (30, 30, 'laminas/Carlos Rodriguez.png'),
  (31, 31, 'laminas/Carlos Vega.png'),
  (32, 32, 'laminas/Carolina Araya.png'),
  (33, 33, 'laminas/Catalina Fuentealba.png'),
  (34, 34, 'laminas/Catalina Mantilla.png'),
  (35, 35, 'laminas/Cesar Matheus.png'),
  (36, 36, 'laminas/Cristian Henriquez.png'),
  (37, 37, 'laminas/Cristian Noguera.png'),
  (38, 38, 'laminas/Cristian Zapata.png'),
  (39, 39, 'laminas/Cristina Molina.png'),
  (40, 40, 'laminas/Cynthia Marchant.png'),
  (41, 41, 'laminas/Daniel Medina.png'),
  (42, 42, 'laminas/Daniela Parra.png'),
  (43, 43, 'laminas/David Barreda.png'),
  (44, 44, 'laminas/David Guarin.png'),
  (45, 45, 'laminas/Derly Florez.png'),
  (46, 46, 'laminas/Diana Sandoval.png'),
  (47, 47, 'laminas/Edward Henao.png'),
  (48, 48, 'laminas/Esteban Aguirre.png'),
  (49, 49, 'laminas/Evelyn Espejo.png'),
  (50, 50, 'laminas/Ezequiel Balasch.png'),
  (51, 51, 'laminas/Felipe Miranda.png'),
  (52, 52, 'laminas/Felipe Weiss.png'),
  (53, 53, 'laminas/Fernanda Florez.png'),
  (54, 54, 'laminas/Francisca Soto.png'),
  (55, 55, 'laminas/Gabriela Jugo.png'),
  (56, 56, 'laminas/Genito Andrade.png'),
  (57, 57, 'laminas/Gerardo Barragan.png'),
  (58, 58, 'laminas/Gonzalo Bertomeu.png'),
  (59, 59, 'laminas/Gonzalo de la Jara.png'),
  (60, 60, 'laminas/Gonzalo Lopez.png'),
  (61, 61, 'laminas/Hector Rojo.png'),
  (62, 62, 'laminas/Ignacio Portilla.png'),
  (63, 63, 'laminas/Israel Flores.png'),
  (64, 64, 'laminas/Jaime Herreros.png'),
  (65, 65, 'laminas/Javier Espinoza.png'),
  (66, 66, 'laminas/Javier Fonseca.png'),
  (67, 67, 'laminas/Javiera Huentemil.png'),
  (68, 68, 'laminas/Jeison Jimenez.png'),
  (69, 69, 'laminas/Jennifer Luengas.png'),
  (70, 70, 'laminas/Jesus Osorio.png'),
  (71, 71, 'laminas/Johan Casanova.png'),
  (72, 72, 'laminas/Johan Rosas.png'),
  (73, 73, 'laminas/Jonathan Sepulveda.png'),
  (74, 74, 'laminas/Jorge Reynoso.png'),
  (75, 75, 'laminas/Jose Manuel Barros.png'),
  (76, 76, 'laminas/Jose Matus.png'),
  (77, 77, 'laminas/Jose Miguel Moreno.png'),
  (78, 78, 'laminas/Jose Romero.png'),
  (79, 79, 'laminas/Juan David Loaiza.png'),
  (80, 80, 'laminas/Juan Ignacio Castro.png'),
  (81, 81, 'laminas/Juan Manuel Zuniga.png'),
  (82, 82, 'laminas/Juan Sebastian Illera.png'),
  (83, 83, 'laminas/Juan Sebastian Silva.png'),
  (84, 84, 'laminas/Juliana Daza.png'),
  (85, 85, 'laminas/Julieth Watson.png'),
  (86, 86, 'laminas/Karina Norambuena.png'),
  (87, 87, 'laminas/Karol Rodriguez.png'),
  (88, 88, 'laminas/Katherin Bustos.png'),
  (89, 89, 'laminas/Kathy Figueroa.png'),
  (90, 90, 'laminas/Laura Hurtado.png'),
  (91, 91, 'laminas/Leonardo Revilla.png'),
  (92, 92, 'laminas/Liliana Jimenez.png'),
  (93, 93, 'laminas/Liliana Martinez.png'),
  (94, 94, 'laminas/Lorena Silva.png'),
  (95, 95, 'laminas/Luis Cova.png'),
  (96, 96, 'laminas/Luisa Aravena.png'),
  (97, 97, 'laminas/Maira Bello.png'),
  (98, 98, 'laminas/Manuel Hernandez.png'),
  (99, 99, 'laminas/Manuel Lamas.png'),
  (100, 100, 'laminas/Marcela Garzon.png'),
  (101, 101, 'laminas/Marcos Butala.png'),
  (102, 102, 'laminas/Maria Cecilia Calderini.png'),
  (103, 103, 'laminas/Maria de los Angeles Pino.png'),
  (104, 104, 'laminas/Maria Fernanda Diaz.png'),
  (105, 105, 'laminas/Maria Jose Maray.png'),
  (106, 106, 'laminas/Marialy Torrealba.png'),
  (107, 107, 'laminas/Mariela Cuahutencos.png'),
  (108, 108, 'laminas/Mariom Soto.png'),
  (109, 109, 'laminas/Marlen Arriagada.png'),
  (110, 110, 'laminas/Martin Gonzalez.png'),
  (111, 111, 'laminas/Martin Sztajn.png'),
  (112, 112, 'laminas/Matt Deacon.png'),
  (113, 113, 'laminas/Mauricio Bustamante.png'),
  (114, 114, 'laminas/Melanie Galuschka.png'),
  (115, 115, 'laminas/Melissa Calderon.png'),
  (116, 116, 'laminas/Mini Arevalo.png'),
  (117, 117, 'laminas/Natali Rodriguez.png'),
  (118, 118, 'laminas/Natalia Cancino.png'),
  (119, 119, 'laminas/Natalia Chandia.png'),
  (120, 120, 'laminas/Natalia Imazio.png'),
  (121, 121, 'laminas/Natalia Vidal.png'),
  (122, 122, 'laminas/Nataly Salinas.png'),
  (123, 123, 'laminas/Olga Torres.png'),
  (124, 124, 'laminas/Orlando Vazquez.png'),
  (125, 125, 'laminas/Pablo Delillo.png'),
  (126, 126, 'laminas/Pablo Ormero.png'),
  (127, 127, 'laminas/Paola Melo.png'),
  (128, 128, 'laminas/Patricio Aliaga.png'),
  (129, 129, 'laminas/Paula Pizarro.png'),
  (130, 130, 'laminas/Paulina Caceres.png'),
  (131, 131, 'laminas/Pilar Castillo.png'),
  (132, 132, 'laminas/Renzo Gola.png'),
  (133, 133, 'laminas/Ricardo Vargas.png'),
  (134, 134, 'laminas/Robert Gutierrez.png'),
  (135, 135, 'laminas/Roberto Catalan.png'),
  (136, 136, 'laminas/Rodrigo Lerzundi.png'),
  (137, 137, 'laminas/Rodrigo Marambio.png'),
  (138, 138, 'laminas/Rodrigo Sepulveda.png'),
  (139, 139, 'laminas/Romina Lugo.png'),
  (140, 140, 'laminas/Ruben Giraldo.png'),
  (141, 141, 'laminas/Santiago Saavedra.png'),
  (142, 142, 'laminas/Saul Ponce.png'),
  (143, 143, 'laminas/Sebastian Maureira.png'),
  (144, 144, 'laminas/Sebastian Riquelme.png'),
  (145, 145, 'laminas/Sergio Carrasco.png'),
  (146, 146, 'laminas/Steven Arias.png'),
  (147, 147, 'laminas/Sussane Henriquez.png'),
  (148, 148, 'laminas/Tatiana Torres.png'),
  (149, 149, 'laminas/Valentin Marchant.png'),
  (150, 150, 'laminas/Valeria Gonzalez.png'),
  (151, 151, 'laminas/Valeska Rivera.png'),
  (152, 152, 'laminas/Victor Bentiboglio.png'),
  (153, 153, 'laminas/Victor Gajardo.png'),
  (154, 154, 'laminas/William Guzman.png'),
  (155, 155, 'laminas/Wolfran Pinzon.png'),
  (156, 156, 'laminas/Yeferson Gomez.png'),
  (157, 157, 'laminas/Rocky.png'),
  (158, 158, 'laminas/Robotito.png'),
  (159, 159, 'laminas/Julio Iglesias.png'),
  (160, 160, 'laminas/Elias Lescano.png')
on conflict (id) do update set
  user_id = excluded.user_id,
  foto_path = excluded.foto_path;

select setval(pg_get_serial_sequence('public.usuarios', 'id'), (select max(id) from public.usuarios), true);
select setval(pg_get_serial_sequence('public.figuritas', 'id'), (select max(id) from public.figuritas), true);

